[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "emdb"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
  "pyperclip >= 1.9",
  # backup_move (from my dotfiles),
]
scripts = {emdb = "emdb.__main__:main"}
